service:
  - name: "hyperhash"
    url_prefix: "/hyperhash"
    server_pool:
      - container_name: "hyperhash-1"
        port: 8000
      - container_name: "hyperhash-2"
        port: 8001
      - container_name: "hyperhash-3"
        port: 8002